const mongoose=require("mongoose")
const ProfileSchema=new mongoose.Schema({
    User:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Users"
    },
    Handle:{
        type:String,
        required:true,
        max:40
    },
    Company:{
        type:String,
        required:true
    },
    Description:{
        type:String,
        required:true
    },
    Website:{
        type:String,
        required:true
    },
    Location:{
        type:String,
        required:true
    },
    Status:{
        type:String,
        required:true
    },
    Skills:{
        type:[String],
        required:true
    },
    Bio:{
        type:String,
        required:true
    },
    Github:{
        type:String,
        required:true
    },
    Linkedin:{
        type:String,
        required:true
    },
    Experience:[{
        Title:{
            type:String,
            required:true
        },
        Company:{
            type:String,
            required:true
        },
        Location:{
            type:String,
            required:true
        },
        From:{
            type:Date,
            required:true
        },
        To:{
            type:Date,
            required:true
        },
        Current:{
            type:Boolean,
            default:False
        },
        Description:{
            type:String,
            required:true,
            max:800
        }}],

        Education:[{
            University:{
                type:String,
                required:true
            },
            Degree:{
                type:String,
                required:true
            },
            FieldOfStudy:{
                type:String,
                required:true
            },
            From:{
                type:Date,
                required:true
            },
            To:{
                type:Date,
                required:true
            },
            Current:{
                type:Boolean,
                default:False
            },
            Description:{
                type:String,
                required:true,
                max:800
            }}],
            Socials:{
                Linkedin:{
                    type:String,
                    required:true
                },
                Github:{
                    type:String,
                    required:true
                },
                Facebook:{
                    type:String,
                    required:true
                },
                Instagram:{
                    type:String,
                    required:true
                },
            }
        
})
module.exports=Profile=mongoose.model("profile",ProfileSchema);